#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <array>

enum brick_points
{
    POINTS_RED = 7,
    POINTS_ORANGE = 5,
    POINTS_GREEN = 3,
    POINTS_YELLOW = 1,
};

const int NUM_BRICK_COLS = 14;
const int NUM_BRICK_ROWS = 8;

const int BRICK_GAP_X = 4;
const int BRICK_GAP_Y = 3;
const int BRICK_WIDTH = 24;
const int BRICK_HEIGHT = 6;

const int BRICK_AREA_WIDTH = NUM_BRICK_COLS * BRICK_WIDTH + (NUM_BRICK_COLS - 1) * BRICK_GAP_X;
const int BRICK_AREA_HEIGHT = NUM_BRICK_ROWS * BRICK_HEIGHT + (NUM_BRICK_ROWS - 1) * BRICK_GAP_Y;
const int BRICK_AREA_Y_START = 150;
const int BRICK_AREA_Y_END = BRICK_AREA_Y_START + BRICK_AREA_HEIGHT;

const int SCREEN_WIDTH = BRICK_AREA_WIDTH;
const int SCREEN_HEIGHT = SCREEN_WIDTH * 1.45;

const int NUM_BRICK_GROUPS = 4;
const int ROWS_PER_GROUP = NUM_BRICK_ROWS / NUM_BRICK_GROUPS;

const std::array<brick_points, 4> BRICK_POINTS = {POINTS_RED, POINTS_ORANGE, POINTS_GREEN, POINTS_YELLOW};
const int MAX_POINTS_PER_SCREEN = ROWS_PER_GROUP * NUM_BRICK_COLS * (BRICK_POINTS[0] + BRICK_POINTS[1] + BRICK_POINTS[2] + BRICK_POINTS[3]);

const int PADDLE_SPEED = 6;
const int PADDLE_HEIGHT = 8;
const int PADDLE_WIDTH = BRICK_WIDTH;
const int PADDLE_Y = SCREEN_HEIGHT - 70;
const int PADDLE_STARTING_X = SCREEN_WIDTH / 2 - PADDLE_WIDTH / 2;

const int BALL_WIDTH = 8;
const int BALL_HEIGHT = 5;
const int BALL_SPAWN_OFFSET = 15;

const int BALL_SPAWN_BOUNDS_LEFT = BALL_SPAWN_OFFSET;
const int BALL_SPAWN_BOUNDS_RIGHT = SCREEN_WIDTH - BALL_SPAWN_OFFSET;
const int BALL_SPAWN_BOUNDS_TOP = BRICK_AREA_Y_END + 25 + BALL_SPAWN_OFFSET;
const int BALL_SPAWN_BOUNDS_BOTTOM = BRICK_AREA_Y_END + 150 - BALL_SPAWN_OFFSET;

const int WALL_WIDTH = 5;
const int WALL_HEIGHT = 18;

const int DIVIDER_START = 55;
const int DIVIDER_END = DIVIDER_START + WALL_HEIGHT;

const int WALL_BOUNDS_END = PADDLE_Y + PADDLE_HEIGHT;

#endif